### ISSUE TITLE
Probability values erroneously detailed in text output of "Plot of proportions by source "

### ISSUE THREAD

**Issue by DiegoNabaesJodar** [AndrewLJackson/siar#16]
largest intervals are labeled as if they were the smallest ones.

EXAMPLE:

>siarproportionbysourceplot(model1,prn=TRUE,grp=1,probs=c(25,75))
Plot of proportions by source 
This requires more than one group in the output file. 
Producing plot..... 
 
Probability values for Group 1 
	 25 % lower = 0.11 upper = 0.28 
	 75 % lower = 0.17 upper = 0.22 
Probability values for Group 2 
	 25 % lower = 0.56 upper = 0.66 
	 75 % lower = 0.6 upper = 0.63

**Comment by AndrewLJackson** [comment]
bug fixed in both `siarproportionbysourceplot` and `siarproportionbygrouplot`. We recommend using `siarhdrs` to extract the credible intervals. We also recommend moving to use the new packages `MixSIAR` or `simmr` instead as `siar` is now out-dated.
