### ISSUE TITLE
siar-devel does not install properly due to architecture hickup

### ISSUE THREAD

**Issue by courtiol** [AndrewLJackson/siar#22]
Hi @AndrewLJackson,

I am currently teaching at a summer school on stable isotope and we tried to play a bit with siar today.

We had a few problems:
- the CRAN version of siar seems to be bugged (overlap.xypolygon missing which confirms issue #5 so overlap() crashes)
- so we tried to install siar from github, so we did not succeed. Using clang (i.e. compiling using MacOS) on an architecture x86_64 the installation works but warn you of a problem:

```{r}
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o siar.so siarmcmcv4.o siarsolomcmcv4.o use.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: ld: warning: ignoring file siarmcmcv4.o, file was built for unsupported file format ( 0x4C 0x01 0x07 0x00 0x00 0x00 0x00 0x00 0x46 0x1A 0x00 0x00 0x1F 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): siarmcmcv4.oignoring file siarsolomcmcv4.o, file was built for unsupported file format ( 0x4C 0x01 0x07 0x00 0x00 0x00 0x00 0x00 0x38 0x16 0x00 0x00 0x1C 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): siarsolomcmcv4.o

ld: warning: ignoring file use.o, file was built for unsupported file format ( 0x4C 0x01 0x07 0x00 0x00 0x00 0x00 0x00 0x4E 0x15 0x00 0x00 0x29 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): use.o
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/siar/libs
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (siar)
```

but using gcc (i.e. on Windows or MacOS; I tried both), the problem makes the compiler crash:

```{r}

*** arch - x64
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o siar.dll tmp.def 
siarmcmcv4.o siarsolomcmcv4.o use.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: 
i386 architecture of input file `siarmcmcv4.o' is incompatible with 
i386:x86-64 output
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: 
i386 architecture of input file `siarsolomcmcv4.o' is incompatible with 
i386:x86-64 output
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe: 
i386 architecture of input file `use.o' is incompatible with i386:x86-64 
output
siarmcmcv4.o:siarmcmcv4.c:(.text+0x14): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x20): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x2c): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x44): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x59): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x6e): more undefined references to 
`_Rprintf' follow
siarmcmcv4.o:siarmcmcv4.c:(.text+0x335): undefined reference to 
`_memset'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x43c): undefined reference to 
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x5aa): undefined reference to 
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x5af): undefined reference to 
`_GetRNGstate'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x5df): undefined reference to 
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x8ac): undefined reference to 
`_Rf_dunif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x8fd): undefined reference to `_clock'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x947): undefined reference to 
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x9ba): undefined reference to 
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xdbb): undefined reference to 
`_Rf_dunif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xe12): undefined reference to 
`_Rf_dunif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xf4e): undefined reference to 
`_PutRNGstate'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xfd7): undefined reference to `_clock'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xfe5): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1007): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x107c): undefined reference to 
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x10ab): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x10d8): undefined reference to 
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x10ee): undefined reference to 
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1124): undefined reference to 
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x113c): undefined reference to `_sqrt'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1155): undefined reference to `_sqrt'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x118e): undefined reference to 
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x11f6): undefined reference to `_sqrt'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1231): undefined reference to 
`_GetRNGstate'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x126f): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x14): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x20): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x2c): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x38): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x50): more undefined 
references to `_Rprintf' follow
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x327): undefined reference to 
`_memset'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x41e): undefined reference to 
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x514): undefined reference to 
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x519): undefined reference to 
`_GetRNGstate'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x546): undefined reference to 
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x696): undefined reference to 
`_sqrt'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x778): undefined reference to 
`_memset'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x84e): undefined reference to 
`_clock'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x892): undefined reference to 
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x8fa): undefined reference to 
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xa57): undefined reference to 
`_sqrt'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xc02): undefined reference to 
`_PutRNGstate'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xc82): undefined reference to 
`_clock'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xc90): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xcb2): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xcfc): undefined reference to 
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd25): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd53): undefined reference to 
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd6c): undefined reference to 
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd8b): undefined reference to 
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xdc0): undefined reference to 
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xe5d): undefined reference to 
`_GetRNGstate'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xeca): undefined reference to 
`_Rprintf'
use.o:use.c:(.text+0x56): undefined reference to `_Rf_dnorm4'
use.o:use.c:(.text+0xa7): undefined reference to `_atan'
use.o:use.c:(.text+0xb7): undefined reference to `_atan'
use.o:use.c:(.text+0xdf): undefined reference to `_exp'
use.o:use.c:(.text+0xef): undefined reference to `_cos'
use.o:use.c:(.text+0x10f): undefined reference to `_exp'
use.o:use.c:(.text+0x11f): undefined reference to `_cos'
use.o:use.c:(.text+0x172): undefined reference to `_Rf_runif'
use.o:use.c:(.text+0x198): undefined reference to `_Rf_runif'
use.o:use.c:(.text+0x1a4): undefined reference to `_cos'
use.o:use.c:(.text+0x1b4): undefined reference to `_tan'
use.o:use.c:(.text+0x1c8): undefined reference to `_log'
use.o:use.c:(.text+0x1ec): undefined reference to `_sqrt'
use.o:use.c:(.text+0x2a7): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x2d3): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x2ff): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x32b): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x387): undefined reference to `_Rf_runif'
use.o:use.c:(.text+0x39b): undefined reference to `_exp'
use.o:use.c:(.text+0x3db): undefined reference to `_log'
use.o:use.c:(.text+0x447): undefined reference to `_log'
use.o:use.c:(.text+0x4cb): undefined reference to `_log'
use.o:use.c:(.text+0x50d): undefined reference to `_log'
use.o:use.c:(.text+0x579): undefined reference to `_log'
use.o:use.c:(.text+0x5d9): more undefined references to `_log' follow
use.o:use.c:(.text+0x705): undefined reference to `_memcpy'
use.o:use.c:(.text+0x987): undefined reference to `_Rf_error'
use.o:use.c:(.text+0x9a8): undefined reference to `_calloc'
use.o:use.c:(.text+0x9be): undefined reference to `_calloc'
use.o:use.c:(.text+0xa58): undefined reference to `_memcpy'
use.o:use.c:(.text+0xb47): undefined reference to `_calloc'
use.o:use.c:(.text+0xb71): undefined reference to `_calloc'
use.o:use.c:(.text+0xbae): undefined reference to `_memcpy'
use.o:use.c:(.text+0xbe4): undefined reference to `_calloc'
use.o:use.c:(.text+0xc0c): undefined reference to `_calloc'
use.o:use.c:(.text+0xc99): undefined reference to `_log'
use.o:use.c:(.text+0xce9): undefined reference to `_calloc'
use.o:use.c:(.text+0xd56): undefined reference to `_log'
collect2.exe: error: ld returned 1 exit status
keine DLL erzeugt
ERROR: compilation failed for package 'siar'
* removing 'C:/Program Files/R/R-3.5.1/library/siar'
* restoring previous 'C:/Program Files/R/R-3.5.1/library/siar'
In R CMD INSTALL
Installation failed: Command failed (1)
```

Any idea of a workaround we could try tomorrow?

Many thanks

Alex

**Comment by AndrewLJackson** [comment]
hi Alex

i dont know is the short answer. Im busy with teaching duties this week and next week also so have only taken a quick look. I too get a warning when building under OSX

> version
               _
platform       x86_64-apple-darwin15.6.0
arch           x86_64
os             darwin15.6.0
system         x86_64, darwin15.6.0
status
major          3
minor          5.1
year           2018
month          07
day            02
svn rev        74947
language       R
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray

I dont have a windows machine nearby to check, but I do know there have been some issues with devtools for windows. See troubleshooting section here https://rawgit.com/andrewcparnell/simms_course/master/Prerequisites.html
 which might help

At this stage, siar is very far out of date and largely unsupported.  I would recommend either MixSIAR https://github.com/brianstock/MixSIAR or simmr https://github.com/andrewcparnell/simmr for smaller more basic mixing models akin to siar.

best wishes

andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/



On 12 Sep 2018, at 16:14, Alexandre Courtiol <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @AndrewLJackson<https://github.com/AndrewLJackson>,

I am currently teaching at a summer school on stable isotope and we tried to play a bit with siar today.

We had a few problems:

  *   the CRAN version of siar seems to be bugged (overlap.xypolygon missing which confirms issue #5<https://github.com/AndrewLJackson/siar/issues/5> so overlap() crashes)
  *   so we tried to install siar from github (although it may still have the same bug), so we did not succeed. Using clang (i.e. compiling using MacOS) on an architecture x86_64 the installation works but warn you of a problem:

clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o siar.so siarmcmcv4.o siarsolomcmcv4.o use.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: ld: warning: ignoring file siarmcmcv4.o, file was built for unsupported file format ( 0x4C 0x01 0x07 0x00 0x00 0x00 0x00 0x00 0x46 0x1A 0x00 0x00 0x1F 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): siarmcmcv4.oignoring file siarsolomcmcv4.o, file was built for unsupported file format ( 0x4C 0x01 0x07 0x00 0x00 0x00 0x00 0x00 0x38 0x16 0x00 0x00 0x1C 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): siarsolomcmcv4.o

ld: warning: ignoring file use.o, file was built for unsupported file format ( 0x4C 0x01 0x07 0x00 0x00 0x00 0x00 0x00 0x4E 0x15 0x00 0x00 0x29 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): use.o
installing to /Library/Frameworks/R.framework/Versions/3.5/Resources/library/siar/libs
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (siar)


but using gcc (i.e. on Windows or MacOS; I tried both), the problem makes the compiler crash:


*** arch - x64
c:/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o siar.dll tmp.def
siarmcmcv4.o siarsolomcmcv4.o use.o -LC:/PROGRA~1/R/R-35~1.1/bin/x64 -lR
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe:
i386 architecture of input file `siarmcmcv4.o' is incompatible with
i386:x86-64 output
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe:
i386 architecture of input file `siarsolomcmcv4.o' is incompatible with
i386:x86-64 output
C:/Rtools/mingw_64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.3/../../../../x86_64-w64-mingw32/bin/ld.exe:
i386 architecture of input file `use.o' is incompatible with i386:x86-64
output
siarmcmcv4.o:siarmcmcv4.c:(.text+0x14): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x20): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x2c): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x44): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x59): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x6e): more undefined references to
`_Rprintf' follow
siarmcmcv4.o:siarmcmcv4.c:(.text+0x335): undefined reference to
`_memset'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x43c): undefined reference to
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x5aa): undefined reference to
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x5af): undefined reference to
`_GetRNGstate'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x5df): undefined reference to
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x8ac): undefined reference to
`_Rf_dunif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x8fd): undefined reference to `_clock'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x947): undefined reference to
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x9ba): undefined reference to
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xdbb): undefined reference to
`_Rf_dunif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xe12): undefined reference to
`_Rf_dunif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xf4e): undefined reference to
`_PutRNGstate'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xfd7): undefined reference to `_clock'
siarmcmcv4.o:siarmcmcv4.c:(.text+0xfe5): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1007): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x107c): undefined reference to
`_Rf_runif'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x10ab): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x10d8): undefined reference to
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x10ee): undefined reference to
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1124): undefined reference to
`_memcpy'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x113c): undefined reference to `_sqrt'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1155): undefined reference to `_sqrt'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x118e): undefined reference to
`_Rprintf'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x11f6): undefined reference to `_sqrt'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x1231): undefined reference to
`_GetRNGstate'
siarmcmcv4.o:siarmcmcv4.c:(.text+0x126f): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x14): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x20): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x2c): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x38): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x50): more undefined
references to `_Rprintf' follow
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x327): undefined reference to
`_memset'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x41e): undefined reference to
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x514): undefined reference to
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x519): undefined reference to
`_GetRNGstate'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x546): undefined reference to
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x696): undefined reference to
`_sqrt'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x778): undefined reference to
`_memset'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x84e): undefined reference to
`_clock'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x892): undefined reference to
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0x8fa): undefined reference to
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xa57): undefined reference to
`_sqrt'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xc02): undefined reference to
`_PutRNGstate'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xc82): undefined reference to
`_clock'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xc90): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xcb2): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xcfc): undefined reference to
`_Rf_runif'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd25): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd53): undefined reference to
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd6c): undefined reference to
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xd8b): undefined reference to
`_memcpy'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xdc0): undefined reference to
`_Rprintf'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xe5d): undefined reference to
`_GetRNGstate'
siarsolomcmcv4.o:siarsolomcmcv4.c:(.text+0xeca): undefined reference to
`_Rprintf'
use.o:use.c:(.text+0x56): undefined reference to `_Rf_dnorm4'
use.o:use.c:(.text+0xa7): undefined reference to `_atan'
use.o:use.c:(.text+0xb7): undefined reference to `_atan'
use.o:use.c:(.text+0xdf): undefined reference to `_exp'
use.o:use.c:(.text+0xef): undefined reference to `_cos'
use.o:use.c:(.text+0x10f): undefined reference to `_exp'
use.o:use.c:(.text+0x11f): undefined reference to `_cos'
use.o:use.c:(.text+0x172): undefined reference to `_Rf_runif'
use.o:use.c:(.text+0x198): undefined reference to `_Rf_runif'
use.o:use.c:(.text+0x1a4): undefined reference to `_cos'
use.o:use.c:(.text+0x1b4): undefined reference to `_tan'
use.o:use.c:(.text+0x1c8): undefined reference to `_log'
use.o:use.c:(.text+0x1ec): undefined reference to `_sqrt'
use.o:use.c:(.text+0x2a7): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x2d3): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x2ff): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x32b): undefined reference to `_Rf_pnorm5'
use.o:use.c:(.text+0x387): undefined reference to `_Rf_runif'
use.o:use.c:(.text+0x39b): undefined reference to `_exp'
use.o:use.c:(.text+0x3db): undefined reference to `_log'
use.o:use.c:(.text+0x447): undefined reference to `_log'
use.o:use.c:(.text+0x4cb): undefined reference to `_log'
use.o:use.c:(.text+0x50d): undefined reference to `_log'
use.o:use.c:(.text+0x579): undefined reference to `_log'
use.o:use.c:(.text+0x5d9): more undefined references to `_log' follow
use.o:use.c:(.text+0x705): undefined reference to `_memcpy'
use.o:use.c:(.text+0x987): undefined reference to `_Rf_error'
use.o:use.c:(.text+0x9a8): undefined reference to `_calloc'
use.o:use.c:(.text+0x9be): undefined reference to `_calloc'
use.o:use.c:(.text+0xa58): undefined reference to `_memcpy'
use.o:use.c:(.text+0xb47): undefined reference to `_calloc'
use.o:use.c:(.text+0xb71): undefined reference to `_calloc'
use.o:use.c:(.text+0xbae): undefined reference to `_memcpy'
use.o:use.c:(.text+0xbe4): undefined reference to `_calloc'
use.o:use.c:(.text+0xc0c): undefined reference to `_calloc'
use.o:use.c:(.text+0xc99): undefined reference to `_log'
use.o:use.c:(.text+0xce9): undefined reference to `_calloc'
use.o:use.c:(.text+0xd56): undefined reference to `_log'
collect2.exe: error: ld returned 1 exit status
keine DLL erzeugt
ERROR: compilation failed for package 'siar'
* removing 'C:/Program Files/R/R-3.5.1/library/siar'
* restoring previous 'C:/Program Files/R/R-3.5.1/library/siar'
In R CMD INSTALL
Installation failed: Command failed (1)


Any idea of a workaround we could try tomorrow?

Many thanks

Alex

**Comment by courtiol** [comment]
Thanks, that helps.

Our issues are not related to devtools and I don't have time to dive into compilation issues as well.
I will fall back to the CRAN version and just do a simple
```{r}
library(spatstat.utils)
```
to bypass issue #5. That should do the trick!

We had plan to work on MixSIAR after siar, but next time perhaps we will indeed start with simmr.
Thanks again,

Alex
