### ISSUE TITLE
Siber.ellipses function using R.3.2.1

### ISSUE THREAD

**Issue by emsa999** [AndrewLJackson/siar#9]
When running siber.ellipses on my own data or even in the example script you provided (demo.SEA_v2), I get an error message that does not allow me to run the rest of the code:

> SEA.B <- siber.ellipses(x,y,group,R=reps)
> Error: not a matrix

This issue does not seem to happen with R3.1.2, but it does with the new R. 3.2.1.

**Comment by AndrewLJackson** [comment]
hi
you will need to update siar to the github hosted version that is ahead of
CRAN.  https://github.com/AndrewLJackson/siar

Simple installation instructions

library(devtools)
install_github("andrewljackson/siar")
library(siar)

cheers

andrew

On 24 June 2015 at 14:40, emsa999 notifications@github.com wrote:

> When running siber.ellipses on my own data or even in the example script
> you provided (demo.SEA_v2), I get an error message that does not allow me
> to run the rest of the code:
> 
> SEA.B <- siber.ellipses(x,y,group,R=reps)
> Error: not a matrix
> 
> This issue does not seem to happen with R3.1.2, but it does with the new
> R. 3.2.1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AndrewLJackson/siar/issues/9.

## 

*You can now follow SIAR on Facebook
http://www.facebook.com/pages/SIAR-Stable-Isotope-Analysis-in-R/148501811896914
or
try my video podcasts
http://www.tcd.ie/Zoology/research/research/theoretical/Rpodcasts.php for
R

Dr Andrew Jackson
Assistant Professor
School of Natural Sciences
Zoology Building, Trinity College Dublin, Dublin 2, Ireland
Tel. + 353 1 896 2728, Fax. + 353 1 677 8094, Email. a.jackson@tcd.ie,
Twitter: @yodacomplex https://twitter.com/yodacomplex
http://www.tcd.ie/Zoology/research/research/theoretical/AndrewJackson.php
